# Generated by Django 5.2.8 on 2025-11-20 06:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("current_chunk", models.IntegerField(default=0)),
                ("total_chunks", models.IntegerField(default=0)),
                ("inserted_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "upload_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OldAgeHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(blank=True, null=True)),
                ("organisation_name", models.CharField(db_index=True, max_length=500)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("city_town_mandal", models.CharField(blank=True, max_length=200)),
                ("po_locality_village", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("pincode", models.CharField(blank=True, max_length=6)),
                ("latitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("longitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("map_location", models.URLField(blank=True, max_length=1000)),
                (
                    "services_type",
                    models.CharField(default="Old Age Home", max_length=100),
                ),
                (
                    "costing_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Free"),
                            ("pay", "Pay"),
                            ("pay_stay", "Pay & Stay"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monthly_charges_minimum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_charges_maximum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("men", "Men"),
                            ("women", "Women"),
                            ("both", "Men & Women"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "care_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic", "Basic Care"),
                            ("nursing", "Nursing Care"),
                            ("day", "Day Care"),
                            ("residential", "Residential Care"),
                            ("palliative", "Palliative Care"),
                        ],
                        max_length=30,
                    ),
                ),
                ("contact_number", models.CharField(blank=True, max_length=500)),
                (
                    "email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "website",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=1000),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "call_verification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("call_verified", "Call Verified"),
                            ("call_not_verified", "Call Not Verified"),
                            ("online_verified", "Online Verified"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "data_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "old_age_homes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "district"],
                        name="old_age_hom_state_a3bbe1_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="old_age_hom_latitud_9297ee_idx",
                    ),
                ],
            },
        ),
    ]
