# Generated by Django 5.2.8 on 2025-11-20 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oldagehome",
            name="contact_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="oldagehome",
            name="email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="oldagehome",
            name="website",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=1000),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
    ]
