# Generated by Django 5.0 on 2026-01-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_alter_oldagehome_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldagehome',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='oldagehome',
            name='batch_no',
            field=models.CharField(blank=True, db_index=True, help_text='Unique batch identifier for this upload job', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='uploadjob',
            name='batch_no',
            field=models.CharField(db_index=True, default='TEMP', help_text='Unique batch identifier for this upload job', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='oldagehome',
            index=models.Index(fields=['batch_no'], name='old_age_hom_batch_n_62934c_idx'),
        ),
    ]
