# Generated by Django 5.0 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_remove_oldagehome_serial_number_oldagehome_batch_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldagehome',
            name='batch_no',
            field=models.CharField(blank=True, db_index=True, help_text='Batch identifier for upload tracking and rollback', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploadjob',
            name='batch_no',
            field=models.CharField(blank=True, db_index=True, help_text='Unique batch identifier for this upload job', max_length=50, null=True, unique=True),
        ),
    ]
