# Generated by Django 5.0 on 2026-04-13 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_alter_oldagehome_batch_no_alter_uploadjob_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldagehome',
            name='contact_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
