# Generated by Django 5.0 on 2026-04-25 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(blank=True, max_length=50)),
                ('client_name', models.CharField(db_column='user_name', max_length=255)),
                ('phone', models.CharField(db_column='user_phone', max_length=50)),
                ('email', models.EmailField(blank=True, db_column='user_email', max_length=254, null=True)),
                ('age', models.IntegerField(blank=True, db_column='user_age', null=True)),
                ('user_country', models.CharField(default='India', max_length=100)),
                ('user_country_other', models.CharField(blank=True, max_length=100, null=True)),
                ('user_state', models.CharField(blank=True, max_length=100)),
                ('user_district', models.CharField(blank=True, max_length=100)),
                ('user_city', models.CharField(blank=True, max_length=100)),
                ('user_area', models.TextField(blank=True)),
                ('user_pincode', models.CharField(blank=True, max_length=20)),
                ('father_age', models.IntegerField(blank=True, null=True)),
                ('mother_age', models.IntegerField(blank=True, null=True)),
                ('relation_type', models.CharField(blank=True, max_length=100)),
                ('relative_name', models.CharField(blank=True, max_length=255)),
                ('relative_age', models.IntegerField(blank=True, null=True)),
                ('client_country', models.CharField(default='India', max_length=100)),
                ('client_country_other', models.CharField(blank=True, max_length=100, null=True)),
                ('client_pincode', models.CharField(blank=True, max_length=20)),
                ('client_state', models.CharField(blank=True, max_length=100)),
                ('client_city', models.CharField(blank=True, max_length=100)),
                ('client_area', models.TextField(blank=True)),
                ('client_condition', models.CharField(blank=True, db_column='health_condition', max_length=255)),
                ('client_condition_other', models.TextField(blank=True, db_column='health_condition_other', null=True)),
                ('client_condition_details', models.TextField(blank=True, db_column='health_condition_details')),
                ('service_types', models.JSONField(blank=True, default=list)),
                ('budget_min', models.IntegerField(blank=True, null=True)),
                ('budget_max', models.IntegerField(blank=True, null=True)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CALLBACK_REQUIRED', 'Callback Required'), ('IN_PROGRESS', 'In Progress'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('SENT_TO_CLIENT', 'Sent to Client'), ('FOLLOW_UP', 'Follow Up'), ('CLOSED', 'Closed')], default='NEW', max_length=50)),
                ('payment_status', models.CharField(default='PENDING', max_length=50)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_link', models.URLField(blank=True, max_length=500, null=True)),
                ('payment_link_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saanidhyam_leads',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_notes', to='ticketing.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
