# Generated by Django 5.0 on 2026-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
