# Generated by Django 5.0 on 2026-04-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_remove_ticket_client_name_ticket_client_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client_condition_other',
        ),
    ]
