# Generated by Django 5.0 on 2026-04-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_oldagehome_contact_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldagehome',
            name='contact_names',
        ),
    ]
